import {ElementShape, ElementType, Element} from './types';

export const DEFAULT_BOARD_LAYOUT_A: Element[] = [
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 47,
    y1: 19,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 27,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 32,
    y1: 27,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 5,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 42,
    y1: 27,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 3,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 50,
    y1: 32,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 4,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 64,
    y1: 17,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 18,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 54,
    y1: 49,
    x2: 5,
    y2: 5,
    stroke: 1,
    fill: 1,
    value: 2,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 42,
    y1: 46,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 26,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 77,
    y1: 15,
    x2: 2,
    y2: 2,
    stroke: 1,
    fill: 1,
    value: 14,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 84,
    y1: 15,
    x2: 2,
    y2: 2,
    stroke: 1,
    fill: 1,
    value: 21,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 91,
    y1: 15,
    x2: 2,
    y2: 2,
    stroke: 1,
    fill: 1,
    value: 20,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 98,
    y1: 15,
    x2: 2,
    y2: 2,
    stroke: 1,
    fill: 1,
    value: 16,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 105,
    y1: 15,
    x2: 2,
    y2: 2,
    stroke: 1,
    fill: 1,
    value: 17,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
];

export const DEFAULT_BOARD_LAYOUT_B: Element[] = [
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 59,
    y1: 27,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 10,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 69,
    y1: 25,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 11,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 79,
    y1: 25,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 12,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 89,
    y1: 27,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 13,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 59,
    y1: 37,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 6,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 69,
    y1: 35,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 7,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 79,
    y1: 35,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 8,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 89,
    y1: 37,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 9,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
  {
    type: ElementType.GP_ELEMENT_PIN_BUTTON,
    x1: 66,
    y1: 45,
    x2: 4,
    y2: 4,
    stroke: 1,
    fill: 1,
    value: 19,
    shape: ElementShape.GP_SHAPE_ELLIPSE,
  },
];
